FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY config/ ./config/
COPY controllers/ ./controllers/
COPY routes/ ./routes/
COPY middleware/ ./middleware/
COPY tests/ ./tests/

EXPOSE 5000
CMD ["python", "app.py"]